blogentry/urls.py
from django.urls import path

from  blogentry.apps import BlogentryConfig
from blogentry.views import BlogentryCreateView, BlogentryListView, BlogentryDetailView, BlogentryUpdateView, \
    BlogentryDeLeteView

app_name = BlogentryConfig.name

urlpatterns = [
    path('create/', BlogentryCreateView.as_view(), name='create'),
    path('', BlogentryListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogentryDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogentryUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogentryDeLeteView.as_view(), name='delete'),



]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogentry/", include("blogentry.urls", namespace="blogentry")),
    path("users/", include("users.urls", namespace="users")),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

]

blogentry/models.py
from django.db import models
from parso.python.tree import Class


class Blogentry(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(max_length=150, unique=True, verbose_name="URL")
    content = models.TextField(verbose_name="Содержание")
    preview = models.ImageField(upload_to='blog_previews/')
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return self.title

blogentry/views.py
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blogentry.models import Blogentry


class BlogentryCreateView(CreateView):
    model = Blogentry
    fields = ('title', 'content')
    success_url = reverse_lazy('blogentry:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)



class BlogentryListView(ListView):
    model = Blogentry

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=False)

        return queryset

class BlogentryDetailView(DetailView):
    model = Blogentry

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

class BlogentryUpdateView(UpdateView):
    model = Blogentry
    fields = ('title', 'content')
    #success_url = reverse_lazy('blogentry:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogentry:view', args=[self.kwargs['pk']])



class BlogentryDeLeteView(DeleteView):
    model = Blogentry
    success_url = reverse_lazy('blogentry:list')

blogentry/templates/blogentry/blogentry_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-5">
<div class ="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                          <p>Вы действительно хотите удалить блог {{ object.title }}?</p>

                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>

                        <a class="btn btn-outline-secondary" href="{% url 'blogentry:list' %}">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

    </div>
</div>

{% endblock %}

blogentry/templates/blogentry/blogentry_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-5">
<div class ="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <p>Блог {{ object.title }}</p>
                        <p>URL: {{ object.slug}}</p>
                    </h3>
                </div>
                  <div class="card-body">
                    <p>
                      {{ object.content }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотров: {{ object.views_count }}
                </div>
            </div>
        </div>
        </div>
    </div>
</div>

    </div>
</div>

{% endblock %}

blogentry/templates/blogentry/blogentry_form.html
{% extends "catalog/base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row mb-5">
<div class ="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

    </div>
</div>

{% endblock %}

blogentry/templates/blogentry/blogentry_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="container mt-5">
    <div class="row mb-5">
        <div class="col-12">
            <a class="btn btn-outline-primary" href="{% url 'blogentry:create' %}">Добавить блог</a>
        </div>
    </div>

    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <h5 class="card-title">Название: {{ object.title }}</h5>
                        <p class="card-text">Описание: {{ object.content | truncatechars:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blogentry:view' object.pk %}" class="btn btn-sm btn-outline-secondary">Посмотреть</a>
                                <a href="{% url 'blogentry:edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Изменить</a>
                                <a href="{% url 'blogentry:delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}