config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogentry/", include("blogentry.urls", namespace="blogentry")),
    path("users/", include("users.urls", namespace="users")),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db import models


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name=_('Email'))
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name=_('Аватар'), )
    phone_number = models.CharField(max_length=15, blank=True, verbose_name=_('Номер телефона'), )
    country = models.CharField(max_length=50, blank=True, verbose_name=_('Страна'))
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    token = models.CharField(max_length=255, verbose_name=_('Токен'), blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserRegistrForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'phone_number', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password1'].widget = forms.HiddenInput()
        self.fields['password2'].widget = forms.HiddenInput()


class EmailForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)

users/views.py
import random
import string
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, FormView
from django.core.mail import send_mail

from users.forms import UserRegistrForm, UserProfileForm
from users.models import User
from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegistrForm
    template_name = "users/register.html"
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()

        url = f"http://{host}/users/email-confirm/{token}/"

        send_mail(
            subject="Подтверждение регистрации",
            message=f"Подтвердите свой аккаунт перейдя по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class PasswordResetView(FormView):
    template_name = 'users/password_reset.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            form.add_error(None, 'Пользователь с таким адресом электронной почты не найден.')
            return self.form_invalid(form)

        new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
        user.password = make_password(new_password)
        user.save()

        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        # subject = 'Восстановление пароля'
        # message = f'Ваш новый пароль: {new_password}'
        # from_email = EMAIL_HOST_USER
        # send_mail(subject, message, from_email, [email])

        return super().form_valid(form)

users/templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Вход</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #f8f9fa;
        }
        .card {
            width: 100%;
            max-width: 400px;
        }
    </style>
</head>
<body>
<div class="card shadow-sm p-4">
    <h2 class="text-center mb-4">Вход</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary w-100">Войти</button>
        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>

    </form>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

users/templates/users/password_reset.html
{% extends "catalog/base.html" %}

{% block content %}
<h2>Восстановление пароля</h2>

<!-- Проверка и вывод сообщений -->
{% if messages %}
<ul>
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- Форма для ввода email -->
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_email">Введите ваш email:</label>
        {{ form.email }}  <!-- Поле email отображается автоматически из формы -->
    </div>
    <button type="submit">Восстановить пароль</button>
</form>
{% endblock %}

users/templates/users/register.html
{% extends "catalog/base.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data " >
    {% csrf_token %}
    <div class="container mt-5">
        <div class="row mb-5">
            <div class="col-12">
                <div class="row">
                    <!-- Колонка с формой продукта -->
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <p>Регистрация</p>
                                </h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    Регистрация
                                </button>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/user_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Вход</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #f8f9fa;
        }
        .card {
            width: 100%;
            max-width: 400px;
        }
    </style>
</head>
<body>
<div class="card shadow-sm p-4">
    <h2 class="text-center mb-4">Профиль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary w-100">Сохранить</button>
    </form>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>