catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductCreateView, ProductListView, ProductDetailView, ProductUpdateView, ProductDeLeteView

app_name = CatalogConfig.name

urlpatterns = [

    path('', cache_page(60 * 15)(ProductListView.as_view()), name='product_list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60 * 15)(ProductDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeLeteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogentry/", include("blogentry.urls", namespace="blogentry")),
    path("users/", include("users.urls", namespace="users")),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, PasswordResetView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

]

catalog/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name="Наименование")
    description = models.TextField(blank=True, verbose_name="Описание")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    STATUS_CHOICES = [
        ('draft', 'Черновик'),
        ('published', 'Опубликован'),
    ]

    name = models.CharField(max_length=255, verbose_name="Наименование")
    description = models.TextField(blank=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="catalog/photo", blank=True, null=True, verbose_name="Изображение"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="Категория",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена за покупку"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Владелец',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft',
        verbose_name='Статус публикации'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name"]
        permissions = [
            ("can_unpublish_product", "Может отменить публикацию продукта"),
            ("can_change_any_product", "Может изменять описание любого продукта"),
            ("can_change_category", "Может изменять категорию любого продукта"),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name="Продукт")
    version_number = models.CharField(max_length=50, verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_current = models.BooleanField(default=False, verbose_name="Текущая версия")

    def __str__(self):
        return f"{self.version_name} ({self.version_number})"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_number"]

catalog/forms.py
from django import forms
from .models import Product


from django import forms
from prompt_toolkit.validation import ValidationError

from .models import Product, Version

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', 'хрен']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'



class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'image', 'price')


    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if any(word in cleaned_data.lower() for word in FORBIDDEN_WORDS):
            raise forms.ValidationError('Название не должно содержать запрещенные слова.')
        return cleaned_data


    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if any(word in cleaned_data.lower() for word in FORBIDDEN_WORDS):
            raise forms.ValidationError('Описание не должно содержать запрещенные слова.')
        return cleaned_data



class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ('product', 'version_number', 'version_name', 'is_current')

class OwnerProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'price', 'image']


class ModeratorProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['description', 'category']

catalog/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.forms import inlineformset_factory

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from .models import Product, Category
from .forms import OwnerProductForm, ModeratorProductForm
from .forms import ProductForm, VersionForm
from .models import Product, Version
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from .services import get_cached_categories


class ProductListView(ListView):
    model = Product

    @method_decorator(cache_page(60 * 15))  # Кеш на 15 минут
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = get_cached_categories()  # Передаем кешированные категории в контекст
        return context


class ProductDetailView(DetailView):
    model = Product

    @method_decorator(cache_page(60 * 15))  # Кеш на 15 минут
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        product = self.get_object()

        if self.request.user.is_superuser:
            return OwnerProductForm  # Суперпользователь получает полную форму

        # Если текущий пользователь является владельцем продукта
        if product.owner == self.request.user:
            return OwnerProductForm  # Полная форма для владельца

        # Если текущий пользователь — модератор и имеет соответствующее разрешение
        if self.request.user.has_perm('catalog.can_change_any_product'):
            return ModeratorProductForm  # Ограниченная форма для модератора

        # Если пользователь не имеет прав для редактирования, выбросим ошибку
        raise PermissionDenied("У вас нет прав для редактирования этого продукта.")

    def get_queryset(self):
        # Модератор может редактировать все продукты, владелец только свои
        if self.request.user.has_perm('catalog.can_change_any_product'):
            return Product.objects.all()
        else:
            return Product.objects.filter(owner=self.request.user)


# class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
#     model = Product
#     fields = ('name', 'description', 'category', 'image', 'price')
#     permission_required = ('catalog.change_product',)
#     success_url = reverse_lazy('catalog:product_list')


class ProductDeLeteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def dispatch(self, request, *args, **kwargs):
        product = self.get_object()

        # Если пользователь является суперпользователем, он может удалять любой продукт
        if request.user.is_superuser:
            return super().dispatch(request, *args, **kwargs)

        # Если текущий пользователь является владельцем продукта, ему разрешено удалять продукт
        if product.owner == request.user:
            return super().dispatch(request, *args, **kwargs)

        # Если пользователь не является владельцем и не суперпользователь, отказ в доступе
        raise PermissionDenied("У вас нет прав для удаления этого продукта.")


# class ProductDeLeteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
#     model = Product
#     permission_required = ('catalog.delete_product',)
#     success_url = reverse_lazy('catalog:product_list')


# class ProductCreateView(LoginRequiredMixin, CreateView):
#     model = Product
#     fields = ('name', 'description', 'category', 'image', 'price')
#     permission_required = ('catalog.add_product',)
#     success_url = reverse_lazy('catalog:product_list')

class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    # fields = ('name', 'description','category','image', 'price')
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html' %}

</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Главная</h1>
                <p>
                    <a href="{% url 'catalog:create' %}" class="btn btn-primary my-2">Добавить</a>
                    <a href="#" class="btn btn-secondary my-2">Secondary action</a>
                </p>
            </div>
        </div>
    </section>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/product_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row mb-5">
<div class ="col-12">
    <div class="row">

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}

                          <p>Вы действительно хотите удалить блог {{ object.name }}?</p>

                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>

                        <a class="btn btn-outline-secondary" href="{% url 'catalog:product_list' %}">Отмена</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row mb-5">

        <div class="col-12">
            <div class="row">
                <!-- Левая колонка с информацией -->
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Информация</h3>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <tr>
                                    <td>Наименование</td>
                                    <td>{{ object.name }}</td>
                                </tr>
                                <tr>
                                    <td>Цена</td>
                                    <td>{{ object.price }}</td>
                                </tr>
                                <tr>
                                    <td>Описание</td>
                                    <td>{{ object.description | truncatechars:50 }}</td>
                                </tr>
                                <tr>
                                    <td>Дата создания</td>
                                    <td>{{ object.created_at }}</td>
                                </tr>
                                <tr>
                                    <td>Дата последнего изменения</td>
                                    <td>{{ object.updated_at }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Назад</a>
                        </div>
                    </div>
                </div>

                <!-- Правая колонка с изображением -->
                <div class="col-6">
                    <div class="card">
                        <div class="card-body d-flex align-items-center justify-content-center" style="height: 100%;">
                            {% if object.image %}
                            <img src="/media/{{ object.image }}" class="img-fluid" alt="Product Image" style="max-height: 100%; max-width: 100%; object-fit: contain;">
                            {% else %}
                            <p>Нет изображения</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}


{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="container mt-5">
        <div class="row mb-5">
            <div class="col-12">
                <div class="row">

                    <!-- Колонка с формой продукта -->
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <p>Добавление продукта</p>
                                </h3>
                            </div>
                            <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                    Сохранить
                                    {% else %}
                                    Создать
                                    {% endif %}
                                </button>
                            </div>
                        </div>
                    </div>

                    <!-- Колонка с изображением продукта -->
                    <div class="col-6">
                        <div class="card" style="height: 100%;">
                            <div class="card-body d-flex align-items-center justify-content-center"
                                 style="height: 100%;">
                                {% if object and object.image %}
                                <img src="{{ object.image.url }}" class="img-fluid" alt="Product Image"
                                     style="max-height: 100%; max-width: 100%; object-fit: contain;">
                                {% else %}
                                <p>Нет изображения</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <!-- Колонка с версиями продукта -->
                    <div class="col-12 mt-4">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <p>Добавление версий</p>
                                </h3>
                            </div>
                            <div class="card-body">
                                {{ formset.management_form }}

                                <div class="d-flex flex-column align-items-start">
                                    <!-- Отображение каждой версии в отдельной карточке -->
                                    {% for form in formset.forms %}
                                    <div class="card mb-3 version-card">
                                        <div class="card-header">
                                            <h5>Версия {{ forloop.counter }}</h5>
                                        </div>
                                        <div class="card-body">
                                            {{ form.as_p }}
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="card-footer"></div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="container mt-5">

    <!-- Добавляем блок для отображения категорий -->
    <div class="row">
    <div class="col-md-3">
        <h5>Категории</h5>
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item">
                {{ category.name }}
            </li>
            {% endfor %}
        </ul>
    </div>


        <div class="col-md-9">
            <div class="col-12 mb-5">
                <div class="row-md-5">
                    <div class="col-12">
                        {% if perms.catalog.add_product %}
                        <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Добавить продукт</a>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="album py-5">
                <div class="container">
                    <div class="row">
                        {% for object in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                {% if object.image %}
                                <img class="card-img-top" src="{{ object.image.url }}" alt="{{ object.name }}"
                                     style="width: 100%; height: 200px; object-fit: cover;">
                                {% else %}
                                <img class="card-img-top" src="{% static 'images/default.png' %}" alt="Default Image"
                                     style="width: 100%; height: 200px; object-fit: cover;">
                                {% endif %}

                                <div class="card-body">
                                    <p class="card-text">
                                        Название: {{ object.name }} <br>
                                        {% if object.get_active_version %}
                                        Активная версия: {{ object.get_active_version.version_name }} ({{
                                        object.get_active_version.version_number }})
                                        {% else %}
                                        Активная версия: не назначена
                                        {% endif %}
                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">

                                            <a href="{% url 'catalog:view' object.pk %}"
                                               class="btn btn-sm btn-outline-secondary">Посмотреть</a>

                                            {% if object.owner == user or perms.catalog.can_change_any_product %}
                                            <a href="{% url 'catalog:edit' object.pk %}"
                                               class="btn btn-sm btn-outline-secondary">Изменить</a>
                                            {% endif %}

                                            {% if user.is_superuser or object.owner == user%}
    <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
{% endif %}

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}